services:
  payment-service-app:
    image: payment-service:latest
    container_name: payment-service-app
    ports:
      - "8081:8080"
      - "5005:5005"  # порт для отладки
    # Полностью переопределяем ENTRYPOINT для отладки
    entrypoint: []
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar app.jar
    environment:
      KEYCLOAK_HOST: keycloak:8080
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: payment-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: payment-db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d payment-db || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command:
      - start-dev
      - --http-port=8080
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8085:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    restart: unless-stopped